name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: install build deps
        run: sudo apt-get install python3-setuptools python3-pip 
      - name: checkout source code
        uses: actions/checkout@v1
      - name: build zip
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt  --target pydeps/
          cd pydeps 
          zip -r9 ${OLDPWD}/function.zip . 
          cd $OLDPWD/src 
          zip -g ${OLDPWD}/function.zip .
      - name: show zip content
        run: unzip -l function.zip
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: api-1-003-a-bee2bee
          zip_file: function.zip
